name: tedx_language_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  video_player: ^2.8.6 #
  amazon_cognito_identity_dart_2: ^1.0.2
  html: ^0.15.4
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8

dependency_overrides:
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo4.1-2.png
